
services:
    redis:
        container_name: redis
        image: redis/redis-stack:6.2.2-v3
        restart: 'always'
        ports:
            - 63790:6379
            - 63791:8001
        volumes:
            - ./data:/data
        command: redis-server --requirepass redis_password