
services:
    redis:
        container_name: redis
        image: redis/redis-stack:latest
        ports:
            - 63790:6379
            - 63791:8001
        volumes:
            - ./data:/data